# Generated by Django 5.2.1 on 2025-05-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='password_hash',
            new_name='password',
        ),
    ]
