# Generated by Django 5.2.1 on 2025-05-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_password_hash_patients_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='password',
            new_name='password_hash',
        ),
    ]
