# Generated by Django 5.2 on 2025-05-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('clinic_location', models.TextField(blank=True, null=True)),
                ('operating_hours', models.TextField(blank=True, null=True)),
                ('education', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
