# Generated by Django 5.2.1 on 2025-05-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=10)),
                ('claimed_by_doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('medical_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='medical_images.medicalimage')),
            ],
        ),
    ]
